### ISSUE TITLE
How do you like the language so far?

### ISSUE THREAD

**Issue by houqp** [baskerville/sketch#1]
Good to see you picked rust for this project! How is it holding up so far? Do you find it a good language for developing apps for embedded devices like kobo readers?

I have been seriously considering rewrite the core of KOReader with rust for awhile. Mostly the UI loop, but perhaps also the widget system. Maybe we can share some of the code in plato ;)

**Comment by baskerville** [comment]
It's holding well, but I haven't reached the hardest part yet: the UI.

**Comment by houqp** [comment]
Nice, I think the hardest part would be getting the toolchain working (which you already did) ;) The rest is just coding and coding.
